Schedulator/Controllers/ProgramsManagementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Schedulator.Models;

namespace Schedulator.Controllers
{
    public class ProgramsManagementController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ProgramsManagement
        public ActionResult Index()
        {
            return View(db.Program.ToList());
        }

        // GET: ProgramsManagement/Details/5
        public ActionResult Details(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Get the program Id
            Program program = db.Program.Find(id);

            if (program == null)
            {
                return HttpNotFound();
            }

            program.CourseSequences = program.CourseSequences.OrderBy(r => r.Year).ThenBy(r => r.Season).ToList();

            return View(program);
        }

        // GET: ProgramsManagement/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProgramsManagement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProgramId,ProgramName,ProgramOption,CreditsRequirement")] Program program)
        {
            if (ModelState.IsValid)
            {
                db.Program.Add(program);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(program);
        }

        //Add course to program
        public ActionResult AddCourse(string searchTerm, int courseSequenceId)
        {
            var courseSequenceData = db.CourseSequence.Find(courseSequenceId);

            var program = courseSequenceData.Program;

            var course = db.Courses.FirstOrDefault(i => (i.CourseLetters + " " + i.CourseNumber) == searchTerm);

            if (course == null)
            {
                return RedirectToAction("EditProgram", new { programId = program.ProgramId, season = courseSequenceData.Season, year = courseSequenceData.Year, error = true});
            }

            var courseToAdd = new CourseSequence
            {
                Season = courseSequenceData.Season,
                Year = courseSequenceData.Year,
                Program = courseSequenceData.Program,
                Course = course
            };

            program.CourseSequences.Add(courseToAdd);
      
             if (ModelState.IsValid)
            {
                db.Entry(program).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("EditProgram", new { programId = program.ProgramId, season = courseSequenceData.Season, year = courseSequenceData.Year, error = false });
            }
            return View(program);
        

        }



        // Edit Program 
        public ActionResult EditProgram(int programId, Season season, int year, bool error = false)
        {
            if(error == true)
                ViewBag.Error = "The Course is invalid.";

            var courses  = db.CourseSequence.Where(i => i.Program.ProgramId == programId && i.Season == season && i.Year == year).ToList();
            
            return View(courses);
        }

        // Delete Course in Program
        public ActionResult DeleteCourse(int? id)
        {
            var data = db.CourseSequence.AsNoTracking().First(i => i.CourseSequenceId == id);
            var pid = data.CourseSequenceId;
            var season = data.Season;
            var year = data.Year;
            CourseSequence course = db.CourseSequence.Find(id);
            db.CourseSequence.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
            
        }

        // POST: ProgramsManagement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCourseConfirmed(int id)
        {
            CourseSequence course = db.CourseSequence.Find(id);
            db.CourseSequence.Remove(course);
            db.SaveChanges();
            return RedirectToAction("EditProgram", new { programId = course.Program.ProgramId, season = course.Season, year = course.Year, error = false });
        }
       
  

        // GET: ProgramsManagement/Edit/5
        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Get the program Id
            Program program = db.Program.Find(id);

            if (program == null)
            {
                return HttpNotFound();
            }
            return View(program);
        }

        // POST: ProgramsManagement/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProgramId,ProgramName,ProgramOption,CreditsRequirement")] Program program)
        {
            if (ModelState.IsValid)
            {
                db.Entry(program).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(program);
        }

        // GET: ProgramsManagement/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Program program = db.Program.Find(id);
            if (program == null)
            {
                return HttpNotFound();
            }
            return View(program);
        }

        // POST: ProgramsManagement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Program program = db.Program.Find(id);
            db.Program.Remove(program);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Schedulator/Views/ProgramsManagement/Create.cshtml
@model Schedulator.Models.Program

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Program</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProgramName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProgramName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProgramName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProgramOption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProgramOption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProgramOption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreditsRequirement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreditsRequirement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditsRequirement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Schedulator/Views/ProgramsManagement/Delete.cshtml
@model Schedulator.Models.Program

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Program</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProgramName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProgramOption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramOption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreditsRequirement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreditsRequirement)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Schedulator/Views/ProgramsManagement/DeleteCourse.cshtml
@model Schedulator.Models.CourseSequence

@{
    ViewBag.Title = "DeleteCourse";
}

<h2>DeleteCourse</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CourseSequence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Season)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Season)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ElectiveType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ElectiveType)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteCourseConfirmed", "ProgramsManagement")) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Schedulator/Views/ProgramsManagement/Details.cshtml
@model Schedulator.Models.Program


@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Program</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Program Name: 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramName)
        </dd>

        <dt>
            Program Option: 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgramOption)
        </dd>

        <dt>
            Credits Requirement: 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreditsRequirement)
        </dd>

    </dl>
</div>

<div>
    <table>
        <tr>    
            <th>Year 1 - Winter @Html.ActionLink("Add Course", "EditProgram", new { programId = Model.ProgramId, season = Schedulator.Models.Season.Fall, year = 1 })</th>     
        </tr>
        <tr>
            <th>Course Number</th>
            <th>Course Name</th>
            <th>Credit</th>
        </tr>
        @{
        var Year = Model.CourseSequences.First().Year;
        var Season = Schedulator.Models.Season.Winter;
        }
       
        @foreach (var item in Model.CourseSequences)
        {
           
            if (item.Season != Season) 
            {
                Year = item.Year;
                Season = item.Season;
                var courses1 = Model.CourseSequences.Where(i => i.Year == Year && i.Season == Season).ToList().Select(i => i.CourseSequenceId );

                <tr>
                    <th>Year @item.Year - @item.Season - @Html.ActionLink("Add Course", "EditProgram", new {programId = Model.ProgramId, season = Season, year = Year})</th>
                </tr>
                <tr>
                    <th>Course Number</th>
                    <th>Course Name</th>
                    <th>Credit</th>
                </tr>
            }            
            if (item.Course != null)
            {
                <tr>                   
                    <td>@item.Course.CourseLetters @item.Course.CourseNumber</td>
                    <td>@item.Course.Title</td>
                    <td>@item.Course.Credit</td>                    
                </tr>
            }
            else
            {
                <tr>
                    <td>@item.ElectiveType</td>
                </tr>
            }

        }
    </table>
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Schedulator/Views/ProgramsManagement/EditProgram.cshtml
@model IEnumerable<Schedulator.Models.CourseSequence>

@{
    ViewBag.Title = "AddCourse";
}

<h2>Edit Program Courses</h2>

@{
    if (ViewBag.Error != ""){
       <h4 class="text-danger">@ViewBag.Error</h4>

    }
}
@using (Html.BeginForm("AddCourse", "ProgramsManagement", new { courseSequenceId = Model.First().CourseSequenceId }))
{
    <div style="float:left; padding: 10px 0 0 100px; width:50%">
        Search: <input type="text" name="searchTerm" style="width: 225px" />
        <input type="submit" value="Add Course" />
        <p>To enter a course, please enter it in this format: Ex: ENGR 213</p>
        
    </div>
}

<table class="table">
    <tr>
        <th>
            Course Number
        </th>
        <th>
            Course Name
        </th>
    </tr>

@foreach (var item in Model) {
    if (item.Course != null) { 
    <tr>
        <td>
            @item.Course.CourseLetters @item.Course.CourseNumber
        </td>
        <td>
            @item.Course.Title
        </td>
        <td>
            @Html.ActionLink("Delete", "DeleteCourse", new { id=item.CourseSequenceId })
        </td>
    </tr>
}
    else
    {
        <tr>
            <td>
                @item.ElectiveType
            </td>
            <td>

            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteCourse", new { id = item.CourseSequenceId })
            </td>
        </tr>
    }
}

</table>

Schedulator/Views/ProgramsManagement/Index.cshtml
@model IEnumerable<Schedulator.Models.Program>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Program Management</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProgramName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProgramOption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreditsRequirement)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProgramName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProgramOption)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreditsRequirement)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.ProgramId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProgramId })
        </td>
    </tr>
}

</table>